### PR TITLE
Add harder TS options

### PR DESCRIPTION
**Pull request by blokhin**

### CODE REVIEW

**Comment by blokhin** [comment]
@PaulMaly please review

**Comment by PaulMaly** [comment]
Hmm, it's a little bit tricky actually. We can't just enable these options without fixing all possible errors/warnings from TS compiler as a result of these changes. So, I think this PR is not complete.

**Review by PaulMaly — CHANGES_REQUESTED** [review]
Hmm, it's a little bit tricky actually. We can't just enable these options without fixing all possible errors/warnings from TS compiler as a result of these changes. So, I think this PR is not complete.

**Comment by blokhin** [comment]
@Valexr please, could you review?

**Comment by Valexr** [comment]
Agree with @PaulMaly with this configs we just need recheck all TS codebase🤷🏻‍♂️

**Review by Valexr — COMMENTED** [review]
Who will check all ts code?

**Comment by blokhin** [comment]
@Valexr @PaulMaly I take a risk 👀

**Pull request merged**
